### ISSUE TITLE
为什么我改了surllist文件会闪退啊？

### ISSUE THREAD

**Issue by chloe5685** [quenlowi/ao3down#1]

**Comment by RoxanneRR** [comment]
你好，你的surllist文件中是否使用的是单引号'？将它改成双引号"试试？
反之，万一你现在用的就是双引号，你可以改成单引号试试
如果还不行的话
①如果你使用的是py文件，把你修改的surllist和编译器报错traceback发上来我看看
②如果你使用的是exe文件，你可以尝试在cmd窗口中运行该exe文件，以获取闪退前的报错信息，然后把你修改的surllist和cmd窗口显示的报错信息发我看看

**Comment by chloe5685** [comment]
> 

啊，我又试了几次，发现是因为我把那个surlist的最后一行也删除了，应该留住的，不好意思打扰了
